Repository ashotvdovychenko/tangerine-web, pull requests merged in 2023-10, with the labels that each got.

#36 Bug/fix vercel multipage 404
  src/index.html
  src/menu-list/menu-list.html
  src/receipt-list/receipt-list.html
  vite.config.js
Labels: bug

#34 List pages base skeleton
  assets/pancake.png
  src/contacts/contacts.html
  src/frequently-asked/frequently-asked.html
  src/index.html
  src/main.js
  src/menu-list/menu-list.html
  src/receipt-list/receipt-list.html
  src/sign-in/sign-in.html
  src/sign-up/sign-up.html
  src/style.css
  vite.config.js
Labels: task, refactor

#39 Add sign-in/sign-up pages
  src/sign-in/sign-in.html
  src/sign-up/sign-up.html
  src/style.css
Labels: task

#40 Info pages content enrichment
  src/contacts/contacts.html
  src/events/events.css
  src/events/events.html
  src/frequently-asked/frequently-asked.css
  src/frequently-asked/frequently-asked.html
  src/index.html
  src/menu-list/menu-list.html
  src/receipt-list/receipt-list.html
  vite.config.js
Labels: task

#41 Fix active buttons color
  src/style.css
Labels: bug

#43 Add vercel.json config
  src/events/events.html
  src/frequently-asked/frequently-asked.html
  src/index.html
  src/menu-list/menu-list.html
  src/receipt-list/receipt-list.html
  src/sign-in/sign-in.html
  src/sign-up/sign-up.html
  vercel.json
Labels: bug
