Repository ashotvdovychenko/tangerine-web, pull requests merged in 2023-09, with the labels that each got.

#12 Bootstrap theme implementation, horizontal scroll fix
  src/index.html
  src/main.js
  src/style.css
Labels: enhancement

#13 Readme vite setup guide update
  README.md
Labels: refactor

#18 README project structure fix
  README.md
Labels: bug, refactor

#21 Basic realization of animated background + section color restyling
  package-lock.json
  package.json
  src/index.html
  src/main.js
  src/style.css
Labels: enhancement

#24 Intall Vercel npm dependency
  package-lock.json
  package.json
Labels: bug

#25 Temporary text refactor
  src/index.html
Labels: refactor

#28 Implement navbar with bootstrap
  src/index.html
  src/main.js
  src/style.css
Labels: enhancement

#27 Temporary images refactor
  assets/advantages-image.png
  assets/burger.png
  assets/cookies.png
  assets/header-background.jpg
  assets/pizza.png
  assets/puncake.png
  assets/questions-image.png
  assets/sushi.png
  src/index.html
  src/main.js
  src/style.css
Labels: enhancement, refactor
